MVCProyect/Models/Empleados.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCMeTieneJarto.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;


    public partial class Empleados
    {
        public int ID { get; set; }
        public string Nombre { get; set; }
        public string Apellido { get; set; }
        [ScaffoldColumn(true)]
        [StringLength(11, ErrorMessage = "La cedula debe tener 11 caracteres")]
        public string Cedula { get; set; }
        public decimal Salario { get; set; }
        public System.DateTime Fecha_ingreso { get; set; }
        public string Telefono { get; set; }
        public string Email { get; set; }
        public int Cargo_ID { get; set; }
        public string Departamento_ID { get; set; }
    
        public virtual Cargos Cargos { get; set; }
        public virtual Departamentos Departamentos { get; set; }
    }
}

MVCProyect/Models/Nomina.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCMeTieneJarto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Nomina
    {
        public int ID { get; set; }
        public int Año { get; set; }
        public int Mes { get; set; }
        public decimal? Nomina1 { get; set; }
    }
}

MVCProyect/Controllers/EmpleadosController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Data.Entity.Validation;
using System.Data.SqlClient;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Web.WebSockets;
using MVCMeTieneJarto.Models;

namespace MVCMeTieneJarto.Controllers
{
    public class EmpleadosController : Controller
    {
        private DbModel db = new DbModel();
        private StoredProceures SP = new StoredProceures();

        // GET: Empleados
        public ActionResult Index()
        {
            var empleados = db.Empleados.Include(e => e.Cargos).Include(e => e.Departamentos);
            return View(empleados.ToList());
        }

        // GET: Empleados/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Empleados empleados = db.Empleados.Find(id);
            if (empleados == null)
            {
                return HttpNotFound();
            }
            return View(empleados);
        }

        // GET: Empleados/Create
        public ActionResult Create()
        {
            ViewBag.Cargo_ID = new SelectList(db.Cargos, "ID", "Cargo");
            ViewBag.Departamento_ID = new SelectList(db.Departamentos, "Codigo", "Nombre");
            return View();
        }

        // POST: Empleados/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que quiere enlazarse. Para obtener 
        // más detalles, vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,Nombre,Apellido,Cedula,Salario,Fecha_ingreso,Telefono,Email,Cargo_ID,Departamento_ID")] Empleados empleados)
        {
            if (ModelState.IsValid)
            { 
                db.Empleados.Add(empleados);
                db.SaveChanges();
                return RedirectToAction("Index");
            }


            ViewBag.Cargo_ID = new SelectList(db.Cargos, "ID", "Cargo", empleados.Cargo_ID);
            ViewBag.Departamento_ID = new SelectList(db.Departamentos, "Codigo", "Nombre", empleados.Departamento_ID);
            return View(empleados);
        }

        // GET: Empleados/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Empleados empleados = db.Empleados.Find(id);
            if (empleados == null)
            {
                return HttpNotFound();
            }
            ViewBag.Cargo_ID = new SelectList(db.Cargos, "ID", "Cargo", empleados.Cargo_ID);
            ViewBag.Departamento_ID = new SelectList(db.Departamentos, "Codigo", "Nombre", empleados.Departamento_ID);
            return View(empleados);
        }

        // POST: Empleados/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que quiere enlazarse. Para obtener 
        // más detalles, vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,Nombre,Apellido,Cedula,Salario,Fecha_ingreso,Telefono,Email,Cargo_ID,Departamento_ID")] Empleados empleados)
        {
            if (ModelState.IsValid)
            {
                db.Entry(empleados).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.Cargo_ID = new SelectList(db.Cargos, "ID", "Cargo", empleados.Cargo_ID);
            ViewBag.Departamento_ID = new SelectList(db.Departamentos, "Codigo", "Nombre", empleados.Departamento_ID);
            return View(empleados);
        }

        // GET: Empleados/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Empleados empleados = db.Empleados.Find(id);
            if (empleados == null)
            {
                return HttpNotFound();
            }
            return View(empleados);
        }

        // POST: Empleados/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Empleados empleados = db.Empleados.Find(id);
            db.Empleados.Remove(empleados);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult CalcularNomina ()
        {
            return View();
        }
        public ActionResult Nomina()
        {
            return View(db.Nomina.ToList());
        }
        public ActionResult generate()
        {
            int year = int.Parse(Request.Form["year"]);
            int month = int.Parse(Request.Form["mes"]);

            
            var result = db.Database.ExecuteSqlCommand("EXEC GetSalaries @year, @month", new SqlParameter("year", SqlDbType.Int) { Value = year },
                new SqlParameter("month", SqlDbType.Int) { Value = month });
            db.SaveChanges();
            return RedirectToAction("Nomina");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

MVCProyect/Views/Empleados/CalcularNomina.cshtml

@{
    ViewBag.Title = "CalcularNomina";
}
    <div class="container">
        <legend class="m-4">Calcular nomina de empleados</legend>
        <p>Por favor introduce el año y mes a partir del los cuales se generara la nomina</p>

        <form class="form" method="post" action="generate">
            <div class="form-group">
                <input placeholder="Año" required type="number" class="form-control" autofocus name="year" id="year" />
            </div>
            <div class="form-group">
                <select placeholder="Año" type="number" class="form-control" name="mes" id="mes">
                    <option value=1>Enero</option>
                    <option value=2>Febrero</option>
                    <option value=3>Marzo</option>
                    <option value=4>Abril</option>
                    <option value=5>Mayo</option>
                    <option value=6>Junio</option>
                    <option value=7>Julio</option>
                    <option value=8>Agosto</option>
                    <option value=9>Septiembre</option>
                    <option value=10>Octubre</option>
                    <option value=11>Noviembre</option>
                    <option value=12>Diciembre</option>
                </select>
            </div>
            <div class="form-group">
                <button class="btn btn-success btn-block" value="generate">
                    Generar Nomina
                </button>
            </div>
        </form>
    </div>



MVCProyect/Views/Empleados/Create.cshtml
@model MVCMeTieneJarto.Models.Empleados

@{
    ViewBag.Title = "Create";
}

<legend class="m-4">Crear Empleados</legend>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Nombre, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nombre, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Apellido, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Apellido, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Apellido, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Cedula, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Cedula, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Cedula, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Salario, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Salario, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Salario, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Fecha_ingreso, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Fecha_ingreso, new { htmlAttributes = new { @class = "form-control", @type = "date" } })
                @Html.ValidationMessageFor(model => model.Fecha_ingreso, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Telefono, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Telefono, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Telefono, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Cargo_ID, "Cargo_ID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Cargo_ID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Cargo_ID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Departamento_ID, "Departamento_ID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Departamento_ID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Departamento_ID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="btn btn-info col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MVCProyect/Views/Empleados/Delete.cshtml
@model MVCMeTieneJarto.Models.Empleados

@{
    ViewBag.Title = "Delete";
}

<legend class="m-4">Eliminar Empleado</legend>

<h3>Are you sure you want to delete this?</h3>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nombre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Apellido)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Apellido)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Cedula)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Cedula)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Salario)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Salario)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Fecha_ingreso)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Fecha_ingreso)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Telefono)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Telefono)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Cargos.Cargo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Cargos.Cargo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Departamentos.Nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Departamentos.Nombre)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

MVCProyect/Views/Empleados/Details.cshtml
@model MVCMeTieneJarto.Models.Empleados

@{
    ViewBag.Title = "Details";
}

<legend class="m-4">Details</legend>

<div>
    <h4>Empleados</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nombre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Apellido)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Apellido)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Cedula)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Cedula)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Salario)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Salario)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Fecha_ingreso)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Fecha_ingreso)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Telefono)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Telefono)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Cargos.Cargo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Cargos.Cargo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Departamentos.Nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Departamentos.Nombre)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ID, @class= "btn btn-info"}) |
    @Html.ActionLink("Back to List", "Index")
</p>

MVCProyect/Views/Empleados/Edit.cshtml
@model MVCMeTieneJarto.Models.Empleados

@{
    ViewBag.Title = "Edit";
}

<legend class="m-4">Editar Empleados</legend>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.Nombre, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nombre, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Apellido, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Apellido, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Apellido, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Cedula, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Cedula, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Cedula, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Salario, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Salario, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Salario, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Fecha_ingreso, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Fecha_ingreso, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Fecha_ingreso, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Telefono, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Telefono, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Telefono, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Cargo_ID, "Cargo_ID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Cargo_ID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Cargo_ID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Departamento_ID, "Departamento_ID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Departamento_ID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Departamento_ID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MVCProyect/Views/Empleados/Index.cshtml
@model IEnumerable<MVCMeTieneJarto.Models.Empleados>

@{
    ViewBag.Title = "Index";
}

<h2 class="m-4">Lista de empleados</h2>


<table class="table">
    <thead class="thead-dark">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Nombre)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Apellido)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Cedula)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Salario)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Fecha_ingreso)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Telefono)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Email)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Cargos.Cargo)
            </th>
            <th>
                Departamento
            </th>
            <th></th>
        </tr>
    </thead>
    

@foreach (var item in Model) {
<tbody>
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Nombre)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Apellido)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Cedula)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Salario)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Fecha_ingreso)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Telefono)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Email)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Cargos.Cargo)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Departamentos.Nombre)
        </td>
        <td>
            @Html.ActionLink("✏️", "Edit", new { id = item.ID }) 
            @Html.ActionLink("🔍", "Details", new { id = item.ID }) 
            @Html.ActionLink("🗑", "Delete", new { id = item.ID })
        </td>
    </tr>
</tbody>
}

</table>

<p>
    @Html.ActionLink("Crear nuevo", "Create", "", new { @class = "btn btn-info btn-block" })
</p>

MVCProyect/Views/Empleados/Nomina.cshtml
@model IEnumerable<MVCMeTieneJarto.Models.Nomina>

@{
    ViewBag.Title = "Nomina";
}

<legend class="m-4">Nomina</legend>

</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Año)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Mes)
        </th>
        <th>
           Nomina
        </th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Año)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Mes)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Nomina1)
        </td>
    </tr>
}

</table>

@Html.ActionLink("Calcular Nomina", "CalcularNomina", "Empleados", new {@class = "btn btn-primary btn-block" })

MVCProyect/Views/Empleados/generate.cshtml

@{
    ViewBag.Title = "generate";
}

<h2>generate</h2>
